### PR TITLE
Fix symlink, walker required / at the end of packagePath for reading …

### PR DESCRIPTION
**Pull request by SSANSH**
…symlink.

### CODE REVIEW

**Comment by nfour** [comment]
How does one replicate this bug?

**Comment by SSANSH** [comment]
Hi, 

You can reproduce this bug by making an external dependency on node_modules.
You can use npm link or lerna link for creating this external dependency.
This will create a symbolic link into node_modules/<your external modules symbolic link>
This external dependency linked by a symbolic link will not be included on bundle without my update and this is the problem.

Thanks.

**Comment by nfour** [comment]
The problem is that your steps to replicate are a usecase that has definitely been supported, explicitly by v2.0. So without a test base to prove this change doesn't break the plugin I can't let it in without at least some way to verify the bug exists and that this fixes it.

**Comment by SSANSH** [comment]
ok, understood,
I will come back newt week with a code for reproducing the bug on your side.

**Comment by SSANSH** [comment]
Please find link to a git project with step to reproduce: 

https://github.com/SSANSH/serverless-build-plugin.bug

**Comment by nfour** [comment]
Looks reasonable, I'm inclined to release an alpha version and to try it on a few projects with complex builds first.

**Comment by nfour** [comment]
@SSANSH try out `serverless-build-plugin@3.1.0-alpha`

**Comment by SSANSH** [comment]
Thanks you for the merge.

**Comment by nfour** [comment]
@SSANSH does this fix it?

**Comment by SSANSH** [comment]
Yes, works fine on my side thanks.

**Pull request merged**
